
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../touch/src",
  "Ext.data.ProxyMgr": "../touch/src/app/Application.js",
  "Ext.device.Purchases.Product": "../touch/src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "../touch/src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "../touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "../touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "../touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "../touch/src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "../touch/src/draw/engine/SvgContext.js",
  "SharedPackageWS1.CustomButton": "../packages/SharedPackageWS1/src-touch/CustomButton.js",
  "SharedPackageWS1.SharedClass": "../packages/SharedPackageWS1/src/SharedClass.js",
  "TouchApp1": "app",
  "TouchPackageWS1.CustomButton": "../packages/TouchPackageWS1/src/CustomButton.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "SharedPackageWS1.CustomButton": [],
  "SharedPackageWS1.SharedClass": [],
  "TouchApp1.view.Main": [],
  "TouchPackageWS1.CustomButton": []
});
Ext.ClassManager.addNameAliasMappings({
  "SharedPackageWS1.CustomButton": [
    "widget.customButtonSharedPackage"
  ],
  "SharedPackageWS1.SharedClass": [],
  "TouchApp1.view.Main": [
    "widget.main"
  ],
  "TouchPackageWS1.CustomButton": [
    "widget.customButtonTouchPackage"
  ]
});
